=== delan/OFBiz/components/service/dtd/service-eca.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  To refer to this DTD in your XML file, use the following declaration:
<!DOCTYPE service-eca PUBLIC "-//OFBiz//DTD Service ECA Config//EN" "http://www.ofbiz.org/dtds/service-eca.dtd">
-->

<!--
 *  Copyright (c) 2002 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a
 *  copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 *  Service Framework - Service ECA Definition DTD
 *  $Id: service-eca.dtd,v 1.1 2003/08/17 05:12:42 ajzeneski Exp $
-->

<!ELEMENT service-eca ( eca+ )>
<!ELEMENT eca ( (condition | condition-field)*, action+ )>
<!ATTLIST eca
    service CDATA #REQUIRED
    event ( auth | in-validate | out-validate | invoke | commit | return ) #REQUIRED
    run-on-error ( true | false ) "false"
>

<!ELEMENT condition EMPTY>
<!ATTLIST condition
    map-name CDATA #IMPLIED
    field-name CDATA #REQUIRED
    operator ( less | greater | less-equals | greater-equals | equals | not-equals | is-empty | is-not-empty | contains ) #REQUIRED
    value CDATA #IMPLIED
    type ( PlainString | String | Double | Float | Long | Integer | Date | Time | Timestamp | Boolean | Object ) "String"
    format CDATA #IMPLIED
>

<!ELEMENT condition-field EMPTY>
<!ATTLIST condition-field
    map-name CDATA #IMPLIED
    field-name CDATA #REQUIRED
    operator ( less | greater | less-equals | greater-equals | equals | not-equals | contains ) #REQUIRED
    to-map-name CDATA #IMPLIED
    to-field-name CDATA #IMPLIED
    type ( PlainString | String | Double | Float | Long | Integer | Date | Time | Timestamp | Boolean | Object ) "String"
    format CDATA #IMPLIED
>

<!ELEMENT action EMPTY>
<!ATTLIST action
    service CDATA #REQUIRED
    mode ( sync | async ) #REQUIRED
    result-map-name CDATA #IMPLIED
    result-to-context ( true | false ) "true"
    ignore-error ( true | false ) "true"
    persist ( true | false ) "false"
>

<!--
<service-eca>
    <eca service="testBsh" event="commit">
      <condition field-name="foo" operator="equals" rhs="1"/>
      <action service="testScv" mode="sync"/>
      <action service="testScv" mode="sync"/>
    </eca>
</service-eca>
-->

=== delan/OFBiz/components/common/servicedef/secas_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE service-eca PUBLIC "-//OFBiz//DTD Service ECA Config//EN" "http://www.ofbiz.org/dtds/service-eca.dtd">

<service-eca>
    <eca service="testScv" event="commit">
        <condition field-name="message" operator="equals" value="12345"/>
        <action service="testBsh" mode="sync"/>
    </eca>
    <eca service="testCommit" event="global-commit">
        <action service="testScv" mode="sync"/>
    </eca>
    <eca service="testRollback" event="global-rollback">
        <action service="testScv" mode="sync"/>
    </eca>
</service-eca>
