=== delan/OFBiz/components/service/dtd/services.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
<!--
  To refer to this Schema in your XML file, use the following declaration:
-->

<!--
 *  Copyright (c) 2001-2004 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a 
 *  copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation 
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, and to permit persons to whom the 
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included 
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *  Service Framework - Service Definition DTD
 *
 *  $Id: $
-->

 <xsd:element name='services'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='description' minOccurs='0' maxOccurs='1'/>
    <xsd:element ref='vendor' minOccurs='0' maxOccurs='1'/>
    <xsd:element ref='version' minOccurs='0' maxOccurs='1'/>
    <xsd:element ref='created' minOccurs='0' maxOccurs='1'/>
    <xsd:element ref='service' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='description'>
  <xsd:complexType>
   <xsd:sequence>
   <xsd:any namespace='http://www.w3.org/namespace/'/>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='namespace'>
  <xsd:complexType>
   <xsd:sequence>
   <xsd:any namespace='http://www.w3.org/namespace/'/>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='vendor' type='xsd:string'>
 </xsd:element>

 <xsd:element name='version' type='xsd:string'>
 </xsd:element>

 <xsd:element name='created' type='xsd:string'>
 </xsd:element>

 <xsd:element name='service'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='description' minOccurs='0' maxOccurs='1'/>
    <xsd:element ref='namespace' minOccurs='0' maxOccurs='1'/>
    <xsd:element ref='required-permissions' minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element ref='implements' minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element ref='auto-attributes' minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element ref='attribute' minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element ref='override' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='name' type='xsd:string' use='required'/>
   <xsd:attribute name='engine' type='xsd:string' use='required'/>
   <xsd:attribute name='location' type='xsd:string' use='required'/>
   <xsd:attribute name='invoke' type='xsd:string' use='required'/>
   <xsd:attribute name='auth' default='false'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='export' default='false'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='validate' default='true'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='default-entity-name' type='xsd:string' use='optional'/>
   <xsd:attribute name='use-transaction' default='true'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='require-new-transaction' default='false'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='transaction-timout' type='xsd:string' use='optional'/>
   <xsd:attribute name='max-retry' type='xsd:string' default='-1'/>
   <xsd:attribute name='debug' default='false'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='required-permissions'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='check-permission' minOccurs='0' maxOccurs='unbounded'/>
    <xsd:element ref='check-role-member' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='join-type' use='required'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='AND'/>
      <xsd:enumeration value='OR'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='check-permission'>
  <xsd:complexType>
   <xsd:attribute name='permission' type='xsd:string' use='required'/>
   <xsd:attribute name='action' type='xsd:string' use='optional'/>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='check-role-member'>
  <xsd:complexType>
   <xsd:attribute name='role-type' type='xsd:string' use='required'/>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='implements'>
  <xsd:complexType>
   <xsd:attribute name='service' type='xsd:string' use='required'/>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='attribute'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='type-validate' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='name' type='xsd:string' use='required'/>
   <xsd:attribute name='type' type='xsd:string' use='required'/>
   <xsd:attribute name='mode' use='required'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='IN'/>
      <xsd:enumeration value='OUT'/>
      <xsd:enumeration value='INOUT'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='form-label' type='xsd:string' use='optional'/>
   <xsd:attribute name='entity-name' type='xsd:string' use='optional'/>
   <xsd:attribute name='field-name' type='xsd:string' use='optional'/>
   <xsd:attribute name='string-map-prefix' type='xsd:string' use='optional'/>
   <xsd:attribute name='string-list-suffix' type='xsd:string' use='optional'/>
   <xsd:attribute name='form-display' default='true'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='optional' default='false'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='exclude'>
  <xsd:complexType>
   <xsd:attribute name='field-name' type='xsd:string' use='required'/>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='auto-attributes'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='exclude' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='entity-name' type='xsd:string' use='optional'/>
   <xsd:attribute name='include' default='all'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='pk'/>
      <xsd:enumeration value='nonpk'/>
      <xsd:enumeration value='all'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='mode' use='required'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='IN'/>
      <xsd:enumeration value='OUT'/>
      <xsd:enumeration value='INOUT'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='form-display' default='true'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='optional' default='false'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='override'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='type-validate' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name='name' type='xsd:string' use='required'/>
   <xsd:attribute name='type' type='xsd:string' use='optional'/>
   <xsd:attribute name='entity-name' type='xsd:string' use='optional'/>
   <xsd:attribute name='field-name' type='xsd:string' use='optional'/>
   <xsd:attribute name='mode' use='optional'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='IN'/>
      <xsd:enumeration value='OUT'/>
      <xsd:enumeration value='INOUT'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='form-label' type='xsd:string' use='optional'/>
   <xsd:attribute name='form-display' use='optional'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
   <xsd:attribute name='optional' use='optional'>
    <xsd:simpleType>
     <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
     </xsd:restriction>
    </xsd:simpleType>
   </xsd:attribute>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='type-validate'>
  <xsd:complexType>
   <xsd:choice>
    <xsd:element ref='fail-message'/>
    <xsd:element ref='fail-property'/>
   </xsd:choice>
   <xsd:attribute name='method' type='xsd:string' use='optional'/>
   <xsd:attribute name='class' type='xsd:string' default='org.ofbiz.base.util.UtilValidate'/>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='fail-message'>
  <xsd:complexType>
   <xsd:attribute name='message' type='xsd:string' use='required'/>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name='fail-property'>
  <xsd:complexType>
   <xsd:attribute name='resource' type='xsd:string' use='required'/>
   <xsd:attribute name='property' type='xsd:string' use='required'/>
  </xsd:complexType>
 </xsd:element>
</xsd:schema>

=== delan/OFBiz/applications/accounting/servicedef/services_invoice.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 *  Copyright (c) 2001-2005 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a
 *  copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="http://www.ofbiz.org/dtds/services.xsd">
    <description>Accounting Services</description>
    <vendor>OFBiz</vendor>
    <version>1.0</version>

    <!-- Invoice services -->
    <service name="createInvoice" engine="simple"
            location="org/ofbiz/accounting/invoice/InvoiceServices.xml" invoke="createInvoice">
        <description>Create Inovice Record</description>
        <attribute name="invoiceTypeId" type="String" mode="IN" optional="false"/>
        <attribute name="partyId" type="String" mode="IN" optional="true"/>
        <attribute name="roleTypeId" type="String" mode="IN" optional="true"/>
        <attribute name="statusId" type="String" mode="IN" optional="false"/>
        <attribute name="billingAccountId" type="String" mode="IN" optional="true"/>
        <attribute name="contactMechId" type="String" mode="IN" optional="true"/>
        <attribute name="invoiceMessage" type="String" mode="IN" optional="true"/>
        <attribute name="description" type="String" mode="IN" optional="true"/>
        <attribute name="invoiceId" type="String" mode="OUT" optional="false"/>
    </service>
    <service name="createInvoiceItem" engine="simple"
            location="org/ofbiz/accounting/invoice/InvoiceServices.xml" invoke="createInvoiceItem">
        <description>Create Invoice Item Record</description>
        <attribute name="invoiceId" type="String" mode="IN" optional="false"/>
        <attribute name="invoiceItemSeqId" type="String" mode="IN" optional="false"/>
        <attribute name="invoiceItemTypeId" type="String" mode="IN" optional="false"/>
        <attribute name="inventoryItemId" type="String" mode="IN" optional="true"/>
        <attribute name="productId" type="String" mode="IN" optional="true"/>
        <attribute name="productFeatureId" type="String" mode="IN" optional="true"/>
        <attribute name="uomId" type="String" mode="IN" optional="true"/>
        <attribute name="taxableFlag" type="Boolean" mode="IN" optional="false"/>
        <attribute name="quantity" type="Double" mode="IN" optional="false"/>
        <attribute name="amount" type="Double" mode="IN" optional="false"/>
        <attribute name="description" type="String" mode="IN" optional="true"/>
    </service>
    <service name="createInvoiceRole" engine="simple"
            location="org/ofbiz/accounting/invoice/InvoiceServices.xml" invoke="createInvoiceRole">
        <description>Create Invoice Role Record</description>
        <attribute name="invoiceId" type="String" mode="IN" optional="false"/>
        <attribute name="partyId" type="String" mode="IN" optional="false"/>
        <attribute name="roleTypeId" type="String" mode="IN" optional="false"/>
        <attribute name="datetimePerformed" type="Timestamp" mode="IN" optional="true"/>
        <attribute name="percentage" type="Double" mode="IN" optional="true"/>
    </service>
    <service name="setInvoiceStatus" engine="simple"
            location="org/ofbiz/accounting/invoice/InvoiceServices.xml" invoke="setInvoiceStatus">
        <description>Create Invoice (Item) Term Record</description>
        <attribute name="statusId" type="String" mode="IN" optional="false"/>
        <attribute name="invoiceId" type="String" mode="IN" optional="false"/>
        <attribute name="statusDate" type="Timestamp" mode="IN" optional="true"/>
    </service>
    <service name="createInvoiceTerm" engine="simple"
            location="org/ofbiz/accounting/invoice/InvoiceServices.xml" invoke="createInvoiceTerm">
        <description>Create Invoice (Item) Term Record</description>
        <attribute name="termTypeId" type="String" mode="IN" optional="false"/>
        <attribute name="invoiceId" type="String" mode="IN" optional="false"/>
        <attribute name="invoiceItemSeqId" type="String" mode="IN" optional="false"/>
        <attribute name="termValue" type="Long" mode="IN" optional="false"/>
        <attribute name="uomId" type="String" mode="IN" optional="true"/>
        <attribute name="invoiceTermId" type="String" mode="OUT" optional="false"/>
    </service>
    <service name="createInvoiceForOrder" engine="java"
            location="org.ofbiz.accounting.invoice.InvoiceServices" invoke="createInvoiceForOrder">
        <description>
                Create an invoice from existing order
                orderId = The orderId to associate the invoice with
                billItems = List of ItemIssuance records to use for creating the invoice
        </description>
        <attribute name="orderId" type="String" mode="IN" optional="false"/>
        <attribute name="billItems" type="List" mode="IN" optional="false"/>
        <attribute name="invoiceId" type="String" mode="OUT" optional="true"/>
    </service>
    <service name="createInvoicesFromShipment" engine="java"
            location="org.ofbiz.accounting.invoice.InvoiceServices" invoke="createInvoicesFromShipment">
        <description>
            Create invoice(s) from a Shipment
            invoicesCreated = List of invoiceIds which were created by this service
        </description>
        <attribute name="shipmentId" type="String" mode="IN" optional="false"/>
        <attribute name="invoicesCreated" type="List" mode="OUT" optional="true"/>
    </service>

    <service name="checkInvoicePaymentApplications" engine="java"
            location="org.ofbiz.accounting.invoice.InvoiceServices" invoke="checkInvoicePaymentApplications">
        <description>Checks to see if the payments applied to an invoice total up to the invoice total; if so sets to PAID</description>
        <attribute name="invoiceId" type="String" mode="IN" optional="false"/>
    </service>
</services>

=== delan/OFBiz/framework/webtools/servicedef/services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  Copyright (c) 2001-2005 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a
 *  copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="http://www.ofbiz.org/dtds/services.xsd">
	<description>OFBiz WebTools Services</description>
	<vendor>OFBiz</vendor>
	<version>1.0</version>

    <!-- Entity Import Services -->
    <service name="parseEntityXmlFile" engine="java" require-new-transaction="true"
            location="org.ofbiz.webtools.WebToolsServices" invoke="parseEntityXmlFile" auth="true">
        <description>Parses an entity xml file or an entity xml text</description>
        <attribute name="url" type="java.net.URL" mode="IN" optional="true"/>
        <attribute name="xmltext" type="String" mode="IN" optional="true"/>
        <attribute name="mostlyInserts" type="String" mode="IN" optional="true"/>
        <attribute name="maintainTimeStamps" type="String" mode="IN" optional="true"/>
        <attribute name="txTimeout" type="Integer" mode="IN" optional="true"/>
        <attribute name="createDummyFks" type="String" mode="IN" optional="true"/>
        <attribute name="rowProcessed" type="Long" mode="OUT" optional="false"/>
    </service>
    <service name="entityImport" engine="java"
            location="org.ofbiz.webtools.WebToolsServices" invoke="entityImport" auth="true">
        <description>Imports an entity xml file or text string</description>
        <attribute name="filename" type="String" mode="IN" optional="true"/>
        <attribute name="fmfilename" type="String" mode="IN" optional="true"/>
        <attribute name="fulltext" type="String" mode="IN" optional="true"/>
        <attribute name="isUrl" type="String" mode="IN" optional="true"/>
        <attribute name="mostlyInserts" type="String" mode="IN" optional="true"/>
        <attribute name="maintainTimeStamps" type="String" mode="IN" optional="true"/>
        <attribute name="createDummyFks" type="String" mode="IN" optional="true"/>
        <attribute name="txTimeout" type="Integer" mode="IN" optional="true"/>
        <attribute name="messages" type="List" mode="OUT" optional="false"/>
    </service>
    <service name="entityImportDir" engine="java"
            location="org.ofbiz.webtools.WebToolsServices" invoke="entityImportDir" auth="true">
        <description>Imports all entity xml files contained in a directory</description>
        <attribute name="path" type="String" mode="IN" optional="true"/>
        <attribute name="mostlyInserts" type="String" mode="IN" optional="true"/>
        <attribute name="maintainTimeStamps" type="String" mode="IN" optional="true"/>
        <attribute name="createDummyFks" type="String" mode="IN" optional="true"/>
        <attribute name="deleteFiles" type="String" mode="IN" optional="true"/>
        <attribute name="txTimeout" type="Integer" mode="IN" optional="true"/>
        <attribute name="filePause" type="Long" mode="IN" optional="true"/>
        <attribute name="messages" type="List" mode="OUT" optional="false"/>
    </service>
    <service name="entityExportAll" engine="java"
            location="org.ofbiz.webtools.WebToolsServices" invoke="entityExportAll" auth="true">
        <description>Exports all entities into xml files</description>
        <attribute name="outpath" type="String" mode="IN" optional="true"/>
        <attribute name="txTimeout" type="Integer" mode="IN" optional="true"/>
        <attribute name="results" type="List" mode="OUT" optional="false"/>
    </service>

</services>
