=== delan/OFBiz/components/entity/dtd/entitygroup.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
<!--
  To refer to this Schema in your XML file, use the following declaration:
-->

<!--
 *  Copyright (c) 2001-2004 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a 
 *  copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation 
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, and to permit persons to whom the 
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included 
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *  $Id: $
-->

<!-- ====================== Root Element ======================= -->
 <xsd:element name='entitygroup'>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref='entity-group' minOccurs='0' maxOccurs='unbounded'/>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

<!-- ================= Children of entitygroup =================== -->
 <xsd:element name='entity-group'>
  <xsd:complexType>
   <xsd:attribute name='group' type='xsd:string' use='required'/>
   <xsd:attribute name='entity' type='xsd:string' use='required'/>
  </xsd:complexType>
 </xsd:element>
</xsd:schema>

=== delan/OFBiz/applications/content/entitydef/entitygroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  Copyright (c) 2001-2005 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a
 *  copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<entitygroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="http://www.ofbiz.org/dtds/entitygroup.xsd">

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.commevent -->
  <!-- ========================================================= -->

	<entity-group group="org.ofbiz" entity="CommEventContentAssoc" />
	<entity-group group="org.ofbiz" entity="CommContentAssocType" />
    <entity-group group="org.ofbiz" entity="CommEventContentDataResource" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.content -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="Content" />
    <entity-group group="org.ofbiz" entity="ContentAndRole" />
    <entity-group group="org.ofbiz" entity="ContentApproval" />
    <entity-group group="org.ofbiz" entity="ContentAssoc" />
    <entity-group group="org.ofbiz" entity="ContentAssocDataResourceViewFrom" />
    <entity-group group="org.ofbiz" entity="ContentAssocDataResourceViewTo" />
    <entity-group group="org.ofbiz" entity="ContentAssocPredicate" />
    <entity-group group="org.ofbiz" entity="ContentAssocType" />
    <entity-group group="org.ofbiz" entity="ContentAssocViewFrom" />
    <entity-group group="org.ofbiz" entity="ContentAssocViewTo" />
    <entity-group group="org.ofbiz" entity="ContentAttribute" />
    <entity-group group="org.ofbiz" entity="ContentDataResourceView" />
    <entity-group group="org.ofbiz" entity="ContentMetaData" />
    <entity-group group="org.ofbiz" entity="ContentOperation" />
    <entity-group group="org.ofbiz" entity="ContentPurpose" />
    <entity-group group="org.ofbiz" entity="ContentPurposeOperation" />
    <entity-group group="org.ofbiz" entity="ContentPurposeType" />
    <entity-group group="org.ofbiz" entity="ContentRevision" />
    <entity-group group="org.ofbiz" entity="ContentRevisionItem" />
    <entity-group group="org.ofbiz" entity="ContentRole" />
    <entity-group group="org.ofbiz" entity="ContentType" />
    <entity-group group="org.ofbiz" entity="ContentTypeAttr" />
    <entity-group group="org.ofbiz" entity="SubContentDataResourceView" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.data -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="CharacterSet" />
    <entity-group group="org.ofbiz" entity="DataCategory" />
    <entity-group group="org.ofbiz" entity="DataResource" />
    <entity-group group="org.ofbiz" entity="DataResourceAttribute" />
    <entity-group group="org.ofbiz" entity="DataResourceContentView" />
    <entity-group group="org.ofbiz" entity="DataResourceMetaData" />
    <entity-group group="org.ofbiz" entity="DataResourcePurpose" />
    <entity-group group="org.ofbiz" entity="DataResourceRole" />
    <entity-group group="org.ofbiz" entity="DataResourceType" />
    <entity-group group="org.ofbiz" entity="DataResourceTypeAttr" />
    <entity-group group="org.ofbiz" entity="DataTemplateType" />
    <entity-group group="org.ofbiz" entity="ElectronicText" />
    <entity-group group="org.ofbiz" entity="FileExtension" />
    <entity-group group="org.ofbiz" entity="ImageDataResource" />
    <entity-group group="org.ofbiz" entity="MetaDataPredicate" />
    <entity-group group="org.ofbiz" entity="MimeType" />
    <entity-group group="org.ofbiz" entity="OtherDataResource" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.document -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="Document" />
    <entity-group group="org.ofbiz" entity="DocumentAttribute" />
    <entity-group group="org.ofbiz" entity="DocumentType" />
    <entity-group group="org.ofbiz" entity="DocumentTypeAttr" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.preference -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="WebPreferenceType" />
    <entity-group group="org.ofbiz" entity="WebUserPreference" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.subscription -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="Subscription" />
    <entity-group group="org.ofbiz" entity="SubscriptionActivity" />
    <entity-group group="org.ofbiz" entity="SubscriptionAttribute" />
    <entity-group group="org.ofbiz" entity="SubscriptionFulfillmentPiece" />
    <entity-group group="org.ofbiz" entity="SubscriptionResource" />
    <entity-group group="org.ofbiz" entity="SubscriptionType" />
    <entity-group group="org.ofbiz" entity="SubscriptionTypeAttr" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.survey -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="Survey" />
    <entity-group group="org.ofbiz" entity="SurveyApplType" />
    <entity-group group="org.ofbiz" entity="SurveyMultiResp" />
    <entity-group group="org.ofbiz" entity="SurveyMultiRespColumn" />
    <entity-group group="org.ofbiz" entity="SurveyPage" />
    <entity-group group="org.ofbiz" entity="SurveyQuestion" />
    <entity-group group="org.ofbiz" entity="SurveyQuestionAndAppl" />
    <entity-group group="org.ofbiz" entity="SurveyQuestionAppl" />
    <entity-group group="org.ofbiz" entity="SurveyQuestionCategory" />
    <entity-group group="org.ofbiz" entity="SurveyQuestionOption" />
    <entity-group group="org.ofbiz" entity="SurveyQuestionType" />
    <entity-group group="org.ofbiz" entity="SurveyResponse" />
    <entity-group group="org.ofbiz" entity="SurveyResponseAndAnswer" />
    <entity-group group="org.ofbiz" entity="SurveyResponseAnswer" />
    <entity-group group="org.ofbiz" entity="SurveyTrigger" />

  <!-- ========================================================= -->
  <!-- org.ofbiz.content.compdoc -->
  <!-- ========================================================= -->

    <entity-group group="org.ofbiz" entity="AssocRevisionItemView" />
    <entity-group group="org.ofbiz" entity="ContentAssocRevisionItemView" />
    <entity-group group="org.ofbiz" entity="MaxRevisionItemView" />
    <entity-group group="org.ofbiz" entity="ContentAssocOptViewFrom" />
    <entity-group group="org.ofbiz" entity="MaxContentApprovalView" />

</entitygroup>
