<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
/**
 *  Title: Entity Generator Definitions for the General Data Model
 *  Description: None
 *  Copyright (c) 2001 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a 
 *  copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation 
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, and to permit persons to whom the 
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included 
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *@author David E. Jones (jonesde@ofbiz.org) 
 *@author Andy Zeneski (jaz@zsolv.com)
 *@version    1.0
 */
-->

<!DOCTYPE entitymodel [
    <!-- ====================== Root Element ======================= -->
    <!ELEMENT entitymodel ( title?, description?, copyright?, author?, version?, entity* )>
    <!-- ================= Children of entitymodel =================== -->
    <!ELEMENT entity ( description?, field*, prim-key*, relation* )>
    <!ELEMENT title ( #PCDATA  )>
    <!ELEMENT description ( #PCDATA  )>
    <!ELEMENT copyright ( #PCDATA  )>
    <!ELEMENT author ( #PCDATA  )>
    <!ELEMENT version ( #PCDATA  )>
    <!-- ================== Children of entity ===================== -->
    <!-- see the children of entitymodel section for description, etc. -->
    <!ATTLIST entity
	entity-name CDATA #REQUIRED >
    <!ATTLIST entity
	table-name CDATA #IMPLIED >
    <!ATTLIST entity
	package-name CDATA #REQUIRED >
    <!ATTLIST entity
	dependent-on CDATA #IMPLIED >
    <!ATTLIST entity
	title CDATA #IMPLIED >
    <!ATTLIST entity
	copyright CDATA #IMPLIED >
    <!ATTLIST entity
	author CDATA #IMPLIED >
    <!ATTLIST entity
	version CDATA #IMPLIED >
    <!ELEMENT field ( validate* )>
    <!ELEMENT prim-key EMPTY>
    <!ATTLIST prim-key
	field CDATA #REQUIRED >
    <!ELEMENT relation ( key-map* )>
    <!-- ==================== Children of field ===================== -->
    <!ATTLIST field
	name CDATA #REQUIRED >
    <!ATTLIST field
	col-name CDATA #IMPLIED >
    <!ATTLIST field
	type CDATA #REQUIRED >
    <!ELEMENT validate EMPTY>
    <!ATTLIST validate
	name CDATA #REQUIRED >
    <!-- ==================== Children of relation ====================== -->
    <!-- specifies whether or not the relation is a dependent one; ie if the related entity can exist without the main entity -->
    <!ATTLIST relation
	type ( one | many ) #REQUIRED >
    <!ATTLIST relation
	title CDATA #IMPLIED >
    <!ATTLIST relation
	rel-entity-name CDATA #REQUIRED >
    <!ATTLIST relation
	rel-table-name CDATA #IMPLIED >
    <!ELEMENT key-map EMPTY>
    <!-- see definition of relation in entity section above -->
    <!-- ===================== Children of key-map ====================== -->
    <!ATTLIST key-map
	field-name CDATA #REQUIRED >
    <!ATTLIST key-map
	rel-field-name CDATA #IMPLIED >
]>


<entitymodel>
  <!-- ========================================================= -->
  <!-- ======================== Defaults ======================= -->
  <!-- ========================================================= -->
    <title>Entity of an Open For Business Project Component</title>
    <description>None</description>
    <copyright>Copyright (c) 2001 The Open For Business Project - www.ofbiz.org</copyright>
    <author>None</author>
    <version>1.0</version>

  <!-- ========================================================= -->
  <!-- ======================== Data Model ===================== -->
  <!-- The modules in this file are as follows:                  -->
  <!--  - org.ofbiz.commonapp.product.category -->
  <!--  - org.ofbiz.commonapp.product.cost -->
  <!--  - org.ofbiz.commonapp.product.feature -->
  <!--  - org.ofbiz.commonapp.product.inventory -->
  <!--  - org.ofbiz.commonapp.product.price -->
  <!--  - org.ofbiz.commonapp.product.product -->
  <!--  - org.ofbiz.commonapp.product.storage -->
  <!--  - org.ofbiz.commonapp.product.supplier -->
  <!-- ========================================================= -->


  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.product.category -->
  <!-- ========================================================= -->
	
    <entity entity-name="ProductCategory" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Entity">
      <field name="productCategoryId" type="id-ne"></field>
      <field name="primaryParentCategoryId" type="id"></field>
      <field name="description" type="description"></field>
      <field name="categoryImageUrl" type="long-varchar"></field>
      <field name="longDescription" type="very-long"></field>	
      <prim-key field="productCategoryId" />
      <relation type="many" rel-entity-name="ProductCategoryClass">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryAttribute">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryMember">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="one" title="PrimaryParent" rel-entity-name="ProductCategory">
        <key-map field-name="primaryParentCategoryId" rel-field-name="productCategoryId" />
      </relation>
      <relation type="many" title="PrimaryChild" rel-entity-name="ProductCategory">
        <key-map field-name="productCategoryId" rel-field-name="primaryParentCategoryId" />
      </relation>
      <relation type="many" title="Primary" rel-entity-name="Product">
        <key-map field-name="productCategoryId" rel-field-name="primaryProductCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="PriceComponent">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="MarketInterest">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="many" title="Current" rel-entity-name="ProductCategoryRollup">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="many" title="Parent" rel-entity-name="ProductCategoryRollup">
        <key-map field-name="productCategoryId" rel-field-name="parentProductCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="SalesTaxLookup">
        <key-map field-name="productCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ProductCategoryAttribute" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Attribute Entity">
      <field name="productCategoryId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>
      <field name="attrValue" type="value"></field>	
      <prim-key field="productCategoryId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="ProductCategory">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryTypeAttr">
        <key-map field-name="attrName" />
      </relation>
    </entity>	
    <entity entity-name="ProductCategoryClass" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Classification Entity">
      <field name="productCategoryId" type="id-ne"></field>
      <field name="productCategoryTypeId" type="id-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>	
      <prim-key field="productCategoryId" />	
      <prim-key field="productCategoryTypeId" />	
      <prim-key field="fromDate" />
      <relation type="one" rel-entity-name="ProductCategory">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="one" rel-entity-name="ProductCategoryType">
        <key-map field-name="productCategoryTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryTypeAttr">
        <key-map field-name="productCategoryTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryAttribute">
        <key-map field-name="productCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ProductCategoryMember" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Member Entity">
      <field name="productCategoryId" type="id-ne"></field>
      <field name="productId" type="id-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>
      <field name="comments" type="comment"></field>	
      <prim-key field="productCategoryId" />	
      <prim-key field="productId" />	
      <prim-key field="fromDate" />
      <relation type="one" rel-entity-name="Product">
        <key-map field-name="productId" />
      </relation>
      <relation type="one" rel-entity-name="ProductCategory">
        <key-map field-name="productCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ProductCategoryRollup" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Rollup Entity">
      <field name="productCategoryId" type="id-ne"></field>
      <field name="parentProductCategoryId" type="id-ne"></field>	
      <prim-key field="productCategoryId" />	
      <prim-key field="parentProductCategoryId" />
      <relation type="one" title="Current" rel-entity-name="ProductCategory">
        <key-map field-name="productCategoryId" />
      </relation>
      <relation type="one" title="Parent" rel-entity-name="ProductCategory">
        <key-map field-name="parentProductCategoryId" rel-field-name="productCategoryId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="ProductCategoryRollup">
        <key-map field-name="productCategoryId" rel-field-name="parentProductCategoryId" />
      </relation>
      <relation type="many" title="Parent" rel-entity-name="ProductCategoryRollup">
        <key-map field-name="parentProductCategoryId" rel-field-name="productCategoryId" />
      </relation>
      <relation type="many" title="Sibling" rel-entity-name="ProductCategoryRollup">
        <key-map field-name="parentProductCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ProductCategoryType" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Type Entity">
      <field name="productCategoryTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="productCategoryTypeId" />
      <relation type="one" title="Parent" rel-entity-name="ProductCategoryType">
        <key-map field-name="parentTypeId" rel-field-name="productCategoryTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="ProductCategoryType">
        <key-map field-name="productCategoryTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryTypeAttr">
        <key-map field-name="productCategoryTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryClass">
        <key-map field-name="productCategoryTypeId" />
      </relation>
    </entity>	
    <entity entity-name="ProductCategoryTypeAttr" 
            package-name="org.ofbiz.commonapp.product.category"
            title="Product Category Type Attribute Entity">
      <field name="productCategoryTypeId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>	
      <prim-key field="productCategoryTypeId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="ProductCategoryType">
        <key-map field-name="productCategoryTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryAttribute">
        <key-map field-name="attrName" />
      </relation>
      <relation type="many" rel-entity-name="ProductCategoryClass">
        <key-map field-name="productCategoryTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.product.cost -->
  <!-- ========================================================= -->
	
    <entity entity-name="CostComponent" 
            package-name="org.ofbiz.commonapp.product.cost"
            title="Cost Component Entity">
      <field name="costComponentId" type="id-ne"></field>
      <field name="costComponentTypeId" type="id"></field>
      <field name="productId" type="id"></field>
      <field name="productFeatureId" type="id"></field>
      <field name="partyId" type="id"></field>
      <field name="geoId" type="id"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>
      <field name="cost" type="currency-amount"></field>	
      <prim-key field="costComponentId" />
      <relation type="one" rel-entity-name="CostComponentType">
        <key-map field-name="costComponentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponentTypeAttr">
        <key-map field-name="costComponentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponentAttribute">
        <key-map field-name="costComponentId" />
      </relation>
      <relation type="one" rel-entity-name="Product">
        <key-map field-name="productId" />
      </relation>
      <relation type="one" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="one" rel-entity-name="Party">
        <key-map field-name="partyId" />
      </relation>
      <relation type="one" rel-entity-name="Geo">
        <key-map field-name="geoId" />
      </relation>
    </entity>	
    <entity entity-name="CostComponentAttribute" 
            package-name="org.ofbiz.commonapp.product.cost"
            title="Cost Component Attribute Entity">
      <field name="costComponentId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>
      <field name="attrValue" type="value"></field>	
      <prim-key field="costComponentId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="CostComponent">
        <key-map field-name="costComponentId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponentTypeAttr">
        <key-map field-name="attrName" />
      </relation>
    </entity>	
    <entity entity-name="CostComponentType" 
            package-name="org.ofbiz.commonapp.product.cost"
            title="Cost Component Type Entity">
      <field name="costComponentTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="costComponentTypeId" />
      <relation type="one" title="Parent" rel-entity-name="CostComponentType">
        <key-map field-name="parentTypeId" rel-field-name="costComponentTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="CostComponentType">
        <key-map field-name="costComponentTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponentTypeAttr">
        <key-map field-name="costComponentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponent">
        <key-map field-name="costComponentTypeId" />
      </relation>
    </entity>	
    <entity entity-name="CostComponentTypeAttr" 
            package-name="org.ofbiz.commonapp.product.cost"
            title="Cost Component Type Attribute Entity">
      <field name="costComponentTypeId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>	
      <prim-key field="costComponentTypeId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="CostComponentType">
        <key-map field-name="costComponentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponentAttribute">
        <key-map field-name="attrName" />
      </relation>
      <relation type="many" rel-entity-name="CostComponent">
        <key-map field-name="costComponentTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.product.feature -->
  <!-- ========================================================= -->
	
    <entity entity-name="FeatureDataObject" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Feature Data Object Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="productFeatureId" type="id-ne"></field>	
      <prim-key field="dataObjectId" />	
      <prim-key field="productFeatureId" />
      <relation type="one" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeature" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Entity">
      <field name="productFeatureId" type="id-ne"></field>
      <field name="productFeatureTypeId" type="id-ne"></field>
      <field name="productFeatureCategoryId" type="id"></field>
      <field name="description" type="description"></field>
      <field name="uomId" type="id"></field>
      <field name="numberSpecified" type="numeric"></field>	
      <prim-key field="productFeatureId" />
      <relation type="one" rel-entity-name="ProductFeatureCategory">
        <key-map field-name="productFeatureCategoryId" />
      </relation>
      <relation type="one" rel-entity-name="ProductFeatureType">
        <key-map field-name="productFeatureTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductFeatureAppl">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="many" title="Main" rel-entity-name="ProductFeatureIactn">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="many" title="Assoc" rel-entity-name="ProductFeatureIactn">
        <key-map field-name="productFeatureId" rel-field-name="productFeatureIdTo" />
      </relation>
      <relation type="many" rel-entity-name="FeatureDataObject">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="many" rel-entity-name="CostComponent">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="many" rel-entity-name="PriceComponent">
        <key-map field-name="productFeatureId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeatureAppl" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Applicability Entity">
      <field name="productId" type="id-ne"></field>
      <field name="productFeatureId" type="id-ne"></field>
      <field name="productFeatureApplTypeId" type="id"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>	
      <prim-key field="productId" />	
      <prim-key field="productFeatureId" />	
      <prim-key field="fromDate" />
      <relation type="one" rel-entity-name="ProductFeatureApplType">
        <key-map field-name="productFeatureApplTypeId" />
      </relation>
      <relation type="one" rel-entity-name="Product">
        <key-map field-name="productId" />
      </relation>
      <relation type="one" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeatureApplType" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Applicability Type Entity">
      <field name="productFeatureApplTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="productFeatureApplTypeId" />
      <relation type="one" title="Parent" rel-entity-name="ProductFeatureApplType">
        <key-map field-name="parentTypeId" rel-field-name="productFeatureApplTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="ProductFeatureApplType">
        <key-map field-name="productFeatureApplTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductFeatureAppl">
        <key-map field-name="productFeatureApplTypeId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeatureCategory" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Category Entity">
      <field name="productFeatureCategoryId" type="id-ne"></field>
      <field name="parentCategoryId" type="id"></field>
      <field name="description" type="description"></field>	
      <prim-key field="productFeatureCategoryId" />
      <relation type="one" rel-entity-name="ProductFeatureCategory">
        <key-map field-name="parentCategoryId" rel-field-name="productFeatureCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeatureIactn" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Interaction Entity">
      <field name="productFeatureId" type="id-ne"></field>
      <field name="productFeatureIdTo" type="id-ne"></field>
      <field name="productFeatureIactnTypeId" type="id"></field>
      <field name="productId" type="id"></field>	
      <prim-key field="productFeatureId" />	
      <prim-key field="productFeatureIdTo" />
      <relation type="one" rel-entity-name="ProductFeatureIactnType">
        <key-map field-name="productFeatureIactnTypeId" />
      </relation>
      <relation type="one" title="Main" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureId" />
      </relation>
      <relation type="one" title="Assoc" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureIdTo" rel-field-name="productFeatureId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeatureIactnType" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Interaction Type Entity">
      <field name="productFeatureIactnTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="productFeatureIactnTypeId" />
      <relation type="one" title="Parent" rel-entity-name="ProductFeatureIactnType">
        <key-map field-name="parentTypeId" rel-field-name="productFeatureIactnTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="ProductFeatureIactnType">
        <key-map field-name="productFeatureIactnTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductFeatureIactn">
        <key-map field-name="productFeatureIactnTypeId" />
      </relation>
    </entity>	
    <entity entity-name="ProductFeatureType" 
            package-name="org.ofbiz.commonapp.product.feature"
            title="Product Feature Type Entity">
      <field name="productFeatureTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="productFeatureTypeId" />
      <relation type="one" title="Parent" rel-entity-name="ProductFeatureType">
        <key-map field-name="parentTypeId" rel-field-name="productFeatureTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="ProductFeatureType">
        <key-map field-name="productFeatureTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ProductFeature">
        <key-map field-name="productFeatureTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.product.inventory -->
  <!-- ========================================================= -->
	
    <entity entity-name="InventoryItem" 
            package-name="org.ofbiz.commonapp.product.inventory"
            title="Inventory Item Entity">
      <field name="inventoryItemId" type="id-ne"></field>
      <field name="inventoryItemTypeId" type="id"></field>
      <field name="productId" type="id"></field>
      <field name="partyId" type="id"></field>
      <field name="statusId" type="id"></field>
      <field name="facilityId" type="id"></field>
      <field name="containerId" type="id"></field>
      <field name="lotId" type="id"></field>
      <field name="uomId" type="id"></field>
      <field name="quantityOnHand" type="floating-point"></field>
      <field name="serialNumber" type="value"></field>	
      <prim-key field="inventoryItemId" />
      <relation type="one" rel-entity-name="InventoryItemType">
        <key-map field-name="inventoryItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InventoryItemTypeAttr">
        <key-map field-name="inventoryItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InventoryItemAttribute">
        <key-map field-name="inventoryItemId" />
      </relation>
      <relation type="one" rel-entity-name="Product">
        <key-map field-name="productId" />
      </relation>
      <relation type="one" rel-entity-name="Party">
        <key-map field-name="partyId" />
      </relation>
      <relation type="one" rel-entity-name="StatusItem">
        <key-map field-name="statusId" />
      </relation>
      <relation type="one" rel-entity-name="Facility">
        <key-map field-name="facilityId" />
      </relation>
      <relation type="one" rel-entity-name="Container">
        <key-map field-name="containerId" />
      </relation>
      <relation type="one" rel-entity-name="Lot">
        <key-map field-name="lotId" />
      </relation>
      <relation type="one" rel-entity-name="Uom">
        <key-map field-name="uomId" />
      </relation>
      <relation type="many" rel-entity-name="InventoryItemVariance">
        <key-map field-name="inventoryItemId" />
      </relation>
      <relation type="many" rel-entity-name="PicklistItem">
        <key-map field-name="inventoryItemId" />
      </relation>
    </entity>	
    <entity entity-name="InventoryItemAttribute" 
            package-name="org.ofbiz.commonapp.product.inventory"
            title="Inventory Item Attribute Entity">
      <field name="inventoryItemId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>
      <field name="attrValue" type="value"></field>	
      <prim-key field="inventoryItemId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="InventoryItem">
        <key-map field-name="inventoryItemId" />
      </relation>
      <relation type="many" rel-entity-name="InventoryItemTypeAttr">
        <key-map field-name="attrName" />
      </relation>
    </entity>	
    <entity entity-name="InventoryItemType" 
            package-name="org.ofbiz.commonapp.product.inventory"
            title="Inventory Item Type Entity">
      <field name="inventoryItemTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="inventoryItemTypeId" />
      <relation type="one" title="Parent" rel-entity-name="InventoryItemType">
        <key-map field-name="parentTypeId" rel-field-name="inventoryItemTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="InventoryItemType">
        <key-map field-name="inventoryItemTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InventoryItemTypeAttr">
        <key-map field-name="inventoryItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InventoryItem">
        <key-map field-name="inventoryItemTypeId" />
      </relation>
    </entity>	
    <entity entity-name="InventoryItemTypeAttr" 
            package-name="org.ofbiz.commonapp.product.inventory"
            title="Inventory Item Type Attribute Entity">
      <field name="inventoryItemTypeId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>	