<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
/**
 *  Title: Entity Generator Definitions for the General Data Model
 *  Description: None
 *  Copyright (c) 2001 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a 
 *  copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation 
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, and to permit persons to whom the 
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included 
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *@author David E. Jones (jonesde@ofbiz.org)
 *@created    Mon Oct 08 17:32:55 EDT 2001
 *@version    1.0
 */
-->

<!DOCTYPE entitymodel [
    <!-- ====================== Root Element ======================= -->
    <!ELEMENT entitymodel ( title?, description?, copyright?, author?, version?, entity* )>
    <!-- ================= Children of entitymodel =================== -->
    <!ELEMENT entity ( description?, field*, prim-key*, relation* )>
    <!ELEMENT title ( #PCDATA  )>
    <!ELEMENT description ( #PCDATA  )>
    <!ELEMENT copyright ( #PCDATA  )>
    <!ELEMENT author ( #PCDATA  )>
    <!ELEMENT version ( #PCDATA  )>
    <!-- ================== Children of entity ===================== -->
    <!-- see the children of entitymodel section for description, etc. -->
    <!ATTLIST entity
	entity-name CDATA #REQUIRED >
    <!ATTLIST entity
	table-name CDATA #IMPLIED >
    <!ATTLIST entity
	package-name CDATA #REQUIRED >
    <!ATTLIST entity
	title CDATA #IMPLIED >
    <!ATTLIST entity
	copyright CDATA #IMPLIED >
    <!ATTLIST entity
	author CDATA #IMPLIED >
    <!ATTLIST entity
	version CDATA #IMPLIED >
    <!ELEMENT field ( validate* )>
    <!ELEMENT prim-key EMPTY>
    <!ATTLIST prim-key
	field CDATA #REQUIRED >
    <!ELEMENT relation ( key-map* )>
    <!-- ==================== Children of field ===================== -->
    <!ATTLIST field
	name CDATA #REQUIRED >
    <!ATTLIST field
	col-name CDATA #IMPLIED >
    <!ATTLIST field
	type CDATA #REQUIRED >
    <!ELEMENT validate EMPTY>
    <!ATTLIST validate
	name CDATA #REQUIRED >
    <!-- ==================== Children of relation ====================== -->
    <!-- specifies whether or not the relation is a dependent one; ie if the related entity can exist without the main entity -->
    <!ATTLIST relation
	type ( one | many ) #REQUIRED >
    <!ATTLIST relation
	title CDATA #IMPLIED >
    <!ATTLIST relation
	rel-entity-name CDATA #REQUIRED >
    <!ATTLIST relation
	rel-table-name CDATA #IMPLIED >
    <!ELEMENT key-map EMPTY>
    <!-- see definition of relation in entity section above -->
    <!-- ===================== Children of key-map ====================== -->
    <!ATTLIST key-map
	field-name CDATA #REQUIRED >
    <!ATTLIST key-map
	col-name CDATA #IMPLIED >
    <!-- this is only required if the field-name in the related table is different from the name in this table -->
    <!ATTLIST key-map
	rel-field-name CDATA #IMPLIED >
    <!-- this is only required if the col-name in the related table is different from the col-name in this table -->
    <!ATTLIST key-map
	rel-col-namee CDATA #IMPLIED >
]>


<entitymodel>
  <!-- ========================================================= -->
  <!-- ======================== Defaults ======================= -->
  <!-- ========================================================= -->
    <title>Entity of an Open For Business Project Component</title>
    <description>None</description>
    <copyright>Copyright (c) 2001 The Open For Business Project - www.ofbiz.org</copyright>
    <author>None</author>
    <version>1.0</version>

  <!-- ========================================================= -->
  <!-- ======================== Data Model ===================== -->
  <!-- The modules in this file are as follows:                  -->
  <!--   - Accounting                                            -->
  <!-- ========================================================= -->


  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.accounting.budget -->
  <!-- ========================================================= -->
	
    <entity entity-name="Budget" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="budgetTypeId" type="id"></field>
      <field name="standardTimePeriodId" type="id"></field>
      <field name="comment" type="comment"></field>	
      <prim-key field="budgetId" />
      <relation type="one" rel-entity-name="BudgetType">
        <key-map field-name="budgetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetTypeAttr">
        <key-map field-name="budgetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetAttribute">
        <key-map field-name="budgetId" />
      </relation>
    </entity>	
    <entity entity-name="BudgetAttribute" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Attribute Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>
      <field name="value" type="value"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="Budget">
        <key-map field-name="budgetId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetTypeAttr">
        <key-map field-name="name" />
      </relation>
    </entity>	
    <entity entity-name="BudgetItem" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Item Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="budgetItemSeqId" type="id-ne"></field>
      <field name="budgetItemTypeId" type="id"></field>
      <field name="amount" type="currency-amount"></field>
      <field name="purpose" type="long-varchar"></field>
      <field name="justification" type="long-varchar"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="budgetItemSeqId" />
      <relation type="one" rel-entity-name="BudgetItemType">
        <key-map field-name="budgetItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItemTypeAttr">
        <key-map field-name="budgetItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItemAttribute">
        <key-map field-name="budgetId" />
        <key-map field-name="budgetItemSeqId" />
      </relation>
    </entity>	
    <entity entity-name="BudgetItemAttribute" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Item Attribute Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="budgetItemSeqId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>
      <field name="value" type="value"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="budgetItemSeqId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="BudgetItem">
        <key-map field-name="budgetId" />
        <key-map field-name="budgetItemSeqId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItemTypeAttr">
        <key-map field-name="name" />
      </relation>
    </entity>	
    <entity entity-name="BudgetItemType" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Item Type Entity">
      <field name="budgetItemTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="budgetItemTypeId" />
      <relation type="one" title="Parent" rel-entity-name="BudgetItemType">
        <key-map field-name="parentTypeId" rel-field-name="budgetItemTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="BudgetItemType">
        <key-map field-name="budgetItemTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItemTypeAttr">
        <key-map field-name="budgetItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItem">
        <key-map field-name="budgetItemTypeId" />
      </relation>
    </entity>	
    <entity entity-name="BudgetItemTypeAttr" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Item Type Attribute Entity">
      <field name="budgetItemTypeId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>	
      <prim-key field="budgetItemTypeId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="BudgetItemType">
        <key-map field-name="budgetItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItemAttribute">
        <key-map field-name="name" />
      </relation>
      <relation type="many" rel-entity-name="BudgetItem">
        <key-map field-name="budgetItemTypeId" />
      </relation>
    </entity>	
    <entity entity-name="BudgetReview" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Review Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="budgetReviewId" type="id-ne"></field>
      <field name="partyId" type="id-ne"></field>
      <field name="budgetReviewResultTypeId" type="id-ne"></field>
      <field name="reviewDate" type="date-time"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="budgetReviewId" />	
      <prim-key field="partyId" />	
      <prim-key field="budgetReviewResultTypeId" />
    </entity>	
    <entity entity-name="BudgetReviewResultType" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Review Result Type Entity">
      <field name="budgetReviewResultTypeId" type="id-ne"></field>
      <field name="description" type="description"></field>
      <field name="comment" type="comment"></field>	
      <prim-key field="budgetReviewResultTypeId" />
    </entity>	
    <entity entity-name="BudgetRevision" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Revision Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="revisionSeqId" type="id-ne"></field>
      <field name="dateRevised" type="date-time"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="revisionSeqId" />
    </entity>	
    <entity entity-name="BudgetRevisionImpact" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Revision Impact Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="budgetItemSeqId" type="id-ne"></field>
      <field name="revisionSeqId" type="id-ne"></field>
      <field name="revisedAmount" type="currency-amount"></field>
      <field name="addDeleteFlag" type="indicator"></field>
      <field name="revisionReason" type="long-varchar"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="budgetItemSeqId" />	
      <prim-key field="revisionSeqId" />
    </entity>	
    <entity entity-name="BudgetRole" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Role Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="partyId" type="id-ne"></field>
      <field name="roleTypeId" type="id-ne"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="partyId" />	
      <prim-key field="roleTypeId" />
    </entity>	
    <entity entity-name="BudgetScenario" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Scenario Entity">
      <field name="budgetScenarioId" type="id-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="budgetScenarioId" />
    </entity>	
    <entity entity-name="BudgetScenarioApplication" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Scenario Application Entity">
      <field name="budgetScenarioApplicId" type="id-ne"></field>
      <field name="budgetScenarioId" type="id-ne"></field>
      <field name="budgetId" type="id"></field>
      <field name="budgetItemSeqId" type="id"></field>
      <field name="amountChange" type="currency-amount"></field>
      <field name="percentageChange" type="floating-point"></field>	
      <prim-key field="budgetScenarioApplicId" />	
      <prim-key field="budgetScenarioId" />
    </entity>	
    <entity entity-name="BudgetScenarioRule" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Scenario Rule Entity">
      <field name="budgetScenarioId" type="id-ne"></field>
      <field name="budgetItemTypeId" type="id-ne"></field>
      <field name="amountChange" type="currency-amount"></field>
      <field name="percentageChange" type="floating-point"></field>	
      <prim-key field="budgetScenarioId" />	
      <prim-key field="budgetItemTypeId" />
    </entity>	
    <entity entity-name="BudgetStatus" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Status Entity">
      <field name="budgetId" type="id-ne"></field>
      <field name="statusId" type="id-ne"></field>
      <field name="statusDate" type="date-time"></field>
      <field name="comment" type="comment"></field>	
      <prim-key field="budgetId" />	
      <prim-key field="statusId" />
    </entity>	
    <entity entity-name="BudgetType" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Type Entity">
      <field name="budgetTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="budgetTypeId" />
      <relation type="one" title="Parent" rel-entity-name="BudgetType">
        <key-map field-name="parentTypeId" rel-field-name="budgetTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="BudgetType">
        <key-map field-name="budgetTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetTypeAttr">
        <key-map field-name="budgetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="Budget">
        <key-map field-name="budgetTypeId" />
      </relation>
    </entity>	
    <entity entity-name="BudgetTypeAttr" 
            package-name="org.ofbiz.commonapp.accounting.budget"
            title="Budget Type Attribute Entity">
      <field name="budgetTypeId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>	
      <prim-key field="budgetTypeId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="BudgetType">
        <key-map field-name="budgetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="BudgetAttribute">
        <key-map field-name="name" />
      </relation>
      <relation type="many" rel-entity-name="Budget">
        <key-map field-name="budgetTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.accounting.fixedasset -->
  <!-- ========================================================= -->
	
    <entity entity-name="Depreciation" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Depreciation Entity">
      <field name="acctgTransId" type="id-ne"></field>
      <field name="assetId" type="id"></field>
      <field name="fixedAssetId" type="id"></field>	
      <prim-key field="acctgTransId" />
    </entity>	
    <entity entity-name="DepreciationMethod" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Depreciation Method Entity">
      <field name="depreciationMethodId" type="id-ne"></field>
      <field name="description" type="description"></field>
      <field name="formula" type="long-varchar"></field>	
      <prim-key field="depreciationMethodId" />
    </entity>	
    <entity entity-name="FixedAsset" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Fixed Asset Entity">
      <field name="fixedAssetId" type="id-ne"></field>
      <field name="fixedAssetTypeId" type="id"></field>
      <field name="partyId" type="id"></field>
      <field name="roleTypeId" type="id"></field>
      <field name="uomId" type="id"></field>
      <field name="name" type="name"></field>
      <field name="dateAcquired" type="date-time"></field>
      <field name="dateLastServiced" type="date-time"></field>
      <field name="dateNextService" type="date-time"></field>
      <field name="productionCapacity" type="floating-point"></field>	
      <prim-key field="fixedAssetId" />
      <relation type="one" rel-entity-name="FixedAssetType">
        <key-map field-name="fixedAssetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="FixedAssetTypeAttr">
        <key-map field-name="fixedAssetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="FixedAssetAttribute">
        <key-map field-name="fixedAssetId" />
      </relation>
    </entity>	
    <entity entity-name="FixedAssetAttribute" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Fixed Asset Attribute Entity">
      <field name="fixedAssetId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>
      <field name="value" type="value"></field>	
      <prim-key field="fixedAssetId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="FixedAsset">
        <key-map field-name="fixedAssetId" />
      </relation>
      <relation type="many" rel-entity-name="FixedAssetTypeAttr">
        <key-map field-name="name" />
      </relation>
    </entity>	
    <entity entity-name="FixedAssetDepMethod" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Fixed Asset Depreciation Method Entity">
      <field name="depreciationMethodId" type="id-ne"></field>
      <field name="fixedAssetId" type="id-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>	
      <prim-key field="depreciationMethodId" />	
      <prim-key field="fixedAssetId" />
    </entity>	
    <entity entity-name="FixedAssetType" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Fixed Asset Type Entity">
      <field name="fixedAssetTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="fixedAssetTypeId" />
      <relation type="one" title="Parent" rel-entity-name="FixedAssetType">
        <key-map field-name="parentTypeId" rel-field-name="fixedAssetTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="FixedAssetType">
        <key-map field-name="fixedAssetTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="FixedAssetTypeAttr">
        <key-map field-name="fixedAssetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="FixedAsset">
        <key-map field-name="fixedAssetTypeId" />
      </relation>
    </entity>	
    <entity entity-name="FixedAssetTypeAttr" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Fixed Asset Type Attribute Entity">
      <field name="fixedAssetTypeId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>	
      <prim-key field="fixedAssetTypeId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="FixedAssetType">
        <key-map field-name="fixedAssetTypeId" />
      </relation>
      <relation type="many" rel-entity-name="FixedAssetAttribute">
        <key-map field-name="name" />
      </relation>
      <relation type="many" rel-entity-name="FixedAsset">
        <key-map field-name="fixedAssetTypeId" />
      </relation>
    </entity>	
    <entity entity-name="PartyFixedAssetAssignment" 
            package-name="org.ofbiz.commonapp.accounting.fixedasset"
            title="Party Fixed Asset Assignment Entity">
      <field name="partyId" type="id-ne"></field>
      <field name="fixedAssetId" type="id-ne"></field>
      <field name="statusId" type="id-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>
      <field name="allocatedDate" type="date-time"></field>
      <field name="comment" type="comment"></field>	
      <prim-key field="partyId" />	
      <prim-key field="fixedAssetId" />	
      <prim-key field="statusId" />	
      <prim-key field="fromDate" />
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.accounting.invoice -->
  <!-- ========================================================= -->
	
    <entity entity-name="Invoice" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Entity">
      <field name="invoiceId" type="id-ne"></field>
      <field name="invoiceTypeId" type="id"></field>
      <field name="partyId" type="id"></field>
      <field name="roleTypeId" type="id"></field>
      <field name="statusId" type="id"></field>
      <field name="billingAccountId" type="id"></field>
      <field name="contactMechId" type="id"></field>
      <field name="invoiceDate" type="date-time"></field>
      <field name="message" type="long-varchar"></field>
      <field name="description" type="description"></field>	
      <prim-key field="invoiceId" />
      <relation type="one" rel-entity-name="InvoiceType">
        <key-map field-name="invoiceTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceTypeAttr">
        <key-map field-name="invoiceTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceAttribute">
        <key-map field-name="invoiceId" />
      </relation>
      <relation type="many" rel-entity-name="OrderItemBilling">
        <key-map field-name="invoiceId" />
      </relation>
    </entity>	
    <entity entity-name="InvoiceAttribute" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Attribute Entity">
      <field name="invoiceId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>
      <field name="value" type="value"></field>	
      <prim-key field="invoiceId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="Invoice">
        <key-map field-name="invoiceId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceTypeAttr">
        <key-map field-name="name" />
      </relation>
    </entity>	
    <entity entity-name="InvoiceItem" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Item Entity">
      <field name="invoiceId" type="id-ne"></field>
      <field name="invoiceItemSeqId" type="id-ne"></field>
      <field name="invoiceItemTypeId" type="id"></field>
      <field name="inventoryItemId" type="id"></field>
      <field name="productId" type="id"></field>
      <field name="productFeatureId" type="id"></field>
      <field name="uomId" type="id"></field>
      <field name="taxableFlag" type="indicator"></field>
      <field name="quantity" type="floating-point"></field>
      <field name="amount" type="currency-amount"></field>
      <field name="description" type="description"></field>	
      <prim-key field="invoiceId" />	
      <prim-key field="invoiceItemSeqId" />
      <relation type="one" rel-entity-name="InvoiceItemType">
        <key-map field-name="invoiceItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItemTypeAttr">
        <key-map field-name="invoiceItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItemAttribute">
        <key-map field-name="invoiceId" />
        <key-map field-name="invoiceItemSeqId" />
      </relation>
      <relation type="many" rel-entity-name="OrderItemBilling">
        <key-map field-name="invoiceId" />
        <key-map field-name="invoiceItemSeqId" />
      </relation>
    </entity>	
    <entity entity-name="InvoiceItemAttribute" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Item Attribute Entity">
      <field name="invoiceId" type="id-ne"></field>
      <field name="invoiceItemSeqId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>
      <field name="value" type="value"></field>	
      <prim-key field="invoiceId" />	
      <prim-key field="invoiceItemSeqId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="InvoiceItem">
        <key-map field-name="invoiceId" />
        <key-map field-name="invoiceItemSeqId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItemTypeAttr">
        <key-map field-name="name" />
      </relation>
    </entity>	
    <entity entity-name="InvoiceItemType" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Item Type Entity">
      <field name="invoiceItemTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="invoiceItemTypeId" />
      <relation type="one" title="Parent" rel-entity-name="InvoiceItemType">
        <key-map field-name="parentTypeId" rel-field-name="invoiceItemTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="InvoiceItemType">
        <key-map field-name="invoiceItemTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItemTypeAttr">
        <key-map field-name="invoiceItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItem">
        <key-map field-name="invoiceItemTypeId" />
      </relation>
    </entity>	
    <entity entity-name="InvoiceItemTypeAttr" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Item Type Attribute Entity">
      <field name="invoiceItemTypeId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>	
      <prim-key field="invoiceItemTypeId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="InvoiceItemType">
        <key-map field-name="invoiceItemTypeId" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItemAttribute">
        <key-map field-name="name" />
      </relation>
      <relation type="many" rel-entity-name="InvoiceItem">
        <key-map field-name="invoiceItemTypeId" />
      </relation>
    </entity>	
    <entity entity-name="InvoiceRole" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Role Entity">
      <field name="invoiceId" type="id-ne"></field>
      <field name="partyId" type="id-ne"></field>
      <field name="roleTypeId" type="id-ne"></field>
      <field name="datetime" type="date-time"></field>
      <field name="percentage" type="floating-point"></field>	
      <prim-key field="invoiceId" />	
      <prim-key field="partyId" />	
      <prim-key field="roleTypeId" />
    </entity>	
    <entity entity-name="InvoiceStatus" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Status Entity">
      <field name="statusId" type="id-ne"></field>
      <field name="invoiceId" type="id-ne"></field>
      <field name="statusDate" type="date-time"></field>	
      <prim-key field="statusId" />	
      <prim-key field="invoiceId" />	
      <prim-key field="statusDate" />
    </entity>	
    <entity entity-name="InvoiceTerm" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Term Entity">
      <field name="invoiceTermId" type="id-ne"></field>
      <field name="termTypeId" type="id"></field>
      <field name="invoiceId" type="id"></field>
      <field name="invoiceItemSeqId" type="id"></field>
      <field name="termValue" type="numeric"></field>	
      <prim-key field="invoiceTermId" />
    </entity>	
    <entity entity-name="InvoiceTermAttribute" 
            package-name="org.ofbiz.commonapp.accounting.invoice"
            title="Invoice Term Attribute Entity">
      <field name="invoiceTermId" type="id-ne"></field>
      <field name="name" type="id-long-ne"></field>
      <field name="value" type="value"></field>	
      <prim-key field="invoiceTermId" />	
      <prim-key field="name" />
      <relation type="one" rel-entity-name="InvoiceTerm">
        <key-map field-name="invoiceTermId" />