<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
/**
 *  Title: Entity Generator Definitions for the General Data Model
 *  Description: None
 *  Copyright (c) 2001 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a 
 *  copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation 
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, and to permit persons to whom the 
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included 
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *@author David E. Jones (jonesde@ofbiz.org)
 *@created    Wed Oct 10 13:29:48 MDT 2001
 *@version    1.0
 */
-->

<!DOCTYPE entitymodel [
    <!-- ====================== Root Element ======================= -->
    <!ELEMENT entitymodel ( title?, description?, copyright?, author?, version?, entity* )>
    <!-- ================= Children of entitymodel =================== -->
    <!ELEMENT entity ( description?, field*, prim-key*, relation* )>
    <!ELEMENT title ( #PCDATA  )>
    <!ELEMENT description ( #PCDATA  )>
    <!ELEMENT copyright ( #PCDATA  )>
    <!ELEMENT author ( #PCDATA  )>
    <!ELEMENT version ( #PCDATA  )>
    <!-- ================== Children of entity ===================== -->
    <!-- see the children of entitymodel section for description, etc. -->
    <!ATTLIST entity
	entity-name CDATA #REQUIRED >
    <!ATTLIST entity
	table-name CDATA #IMPLIED >
    <!ATTLIST entity
	package-name CDATA #REQUIRED >
    <!ATTLIST entity
	title CDATA #IMPLIED >
    <!ATTLIST entity
	copyright CDATA #IMPLIED >
    <!ATTLIST entity
	author CDATA #IMPLIED >
    <!ATTLIST entity
	version CDATA #IMPLIED >
    <!ELEMENT field ( validate* )>
    <!ELEMENT prim-key EMPTY>
    <!ATTLIST prim-key
	field CDATA #REQUIRED >
    <!ELEMENT relation ( key-map* )>
    <!-- ==================== Children of field ===================== -->
    <!ATTLIST field
	name CDATA #REQUIRED >
    <!ATTLIST field
	col-name CDATA #IMPLIED >
    <!ATTLIST field
	type CDATA #REQUIRED >
    <!ELEMENT validate EMPTY>
    <!ATTLIST validate
	name CDATA #REQUIRED >
    <!-- ==================== Children of relation ====================== -->
    <!-- specifies whether or not the relation is a dependent one; ie if the related entity can exist without the main entity -->
    <!ATTLIST relation
	type ( one | many ) #REQUIRED >
    <!ATTLIST relation
	title CDATA #IMPLIED >
    <!ATTLIST relation
	rel-entity-name CDATA #REQUIRED >
    <!ATTLIST relation
	rel-table-name CDATA #IMPLIED >
    <!ELEMENT key-map EMPTY>
    <!-- see definition of relation in entity section above -->
    <!-- ===================== Children of key-map ====================== -->
    <!ATTLIST key-map
	field-name CDATA #REQUIRED >
    <!ATTLIST key-map
	col-name CDATA #IMPLIED >
    <!-- this is only required if the field-name in the related table is different from the name in this table -->
    <!ATTLIST key-map
	rel-field-name CDATA #IMPLIED >
    <!-- this is only required if the col-name in the related table is different from the col-name in this table -->
    <!ATTLIST key-map
	rel-col-namee CDATA #IMPLIED >
]>


<entitymodel>
  <!-- ========================================================= -->
  <!-- ======================== Defaults ======================= -->
  <!-- ========================================================= -->
    <title>Entity of an Open For Business Project Component</title>
    <description>None</description>
    <copyright>Copyright (c) 2001 The Open For Business Project - www.ofbiz.org</copyright>
    <author>None</author>
    <version>1.0</version>

  <!-- ========================================================= -->
  <!-- ======================== Data Model ===================== -->
  <!-- The modules in this file are as follows:                  -->
  <!--  - org.ofbiz.commonapp.common.geo -->
  <!--  - org.ofbiz.commonapp.common.period -->
  <!--  - org.ofbiz.commonapp.common.sequence -->
  <!--  - org.ofbiz.commonapp.common.status -->
  <!--  - org.ofbiz.commonapp.common.uom -->
  <!--  - org.ofbiz.commonapp.content.content -->
  <!--  - org.ofbiz.commonapp.content.document -->
  <!--  - org.ofbiz.commonapp.content.preference -->
  <!--  - org.ofbiz.commonapp.content.subscription -->
  <!--  - org.ofbiz.commonapp.content.visit -->
  <!--  - org.ofbiz.commonapp.security.login -->
  <!--  - org.ofbiz.commonapp.security.securitygroup -->
  <!-- ========================================================= -->


  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.common.geo -->
  <!-- ========================================================= -->
	
    <entity entity-name="Geo" 
            package-name="org.ofbiz.commonapp.common.geo"
            title="Geographic Boundary Entity">
      <field name="geoId" type="id-ne"></field>
      <field name="geoTypeId" type="id"></field>
      <field name="geoName" type="name"></field>
      <field name="geoCode" type="short-varchar"></field>
      <field name="abbreviation" type="short-varchar"></field>	
      <prim-key field="geoId" />
      <relation type="one" rel-entity-name="GeoType">
        <key-map field-name="geoTypeId" />
      </relation>
      <relation type="many" title="Main" rel-entity-name="GeoAssoc">
        <key-map field-name="geoId" />
      </relation>
      <relation type="many" title="Assoc" rel-entity-name="GeoAssoc">
        <key-map field-name="geoId" rel-field-name="geoIdTo" />
      </relation>
      <relation type="many" rel-entity-name="PostalAddressBoundary">
        <key-map field-name="geoId" />
      </relation>
    </entity>	
    <entity entity-name="GeoAssoc" 
            package-name="org.ofbiz.commonapp.common.geo"
            title="Geographic Boundary Association Entity">
      <field name="geoId" type="id-ne"></field>
      <field name="geoIdTo" type="id-ne"></field>
      <field name="geoAssocTypeId" type="id"></field>	
      <prim-key field="geoId" />	
      <prim-key field="geoIdTo" />
      <relation type="one" title="Main" rel-entity-name="Geo">
        <key-map field-name="geoId" />
      </relation>
      <relation type="one" title="Assoc" rel-entity-name="Geo">
        <key-map field-name="geoIdTo" rel-field-name="geoId" />
      </relation>
      <relation type="one" rel-entity-name="GeoAssocType">
        <key-map field-name="geoAssocTypeId" />
      </relation>
    </entity>	
    <entity entity-name="GeoAssocType" 
            package-name="org.ofbiz.commonapp.common.geo"
            title="Geographic Boundary Association Entity">
      <field name="geoAssocTypeId" type="id-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="geoAssocTypeId" />
      <relation type="many" rel-entity-name="GeoAssoc">
        <key-map field-name="geoAssocTypeId" />
      </relation>
    </entity>	
    <entity entity-name="GeoType" 
            package-name="org.ofbiz.commonapp.common.geo"
            title="Geographic Boundary Type Entity">
      <field name="geoTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="geoTypeId" />
      <relation type="one" title="Parent" rel-entity-name="GeoType">
        <key-map field-name="parentTypeId" rel-field-name="geoTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="GeoType">
        <key-map field-name="geoTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="Geo">
        <key-map field-name="geoTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.common.period -->
  <!-- ========================================================= -->
	
    <entity entity-name="PeriodType" 
            package-name="org.ofbiz.commonapp.common.period"
            title="Period Type Entity">
      <field name="periodTypeId" type="id-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="periodTypeId" />
    </entity>	
    <entity entity-name="StandardTimePeriod" 
            package-name="org.ofbiz.commonapp.common.period"
            title="Standard Time Period Entity">
      <field name="standardTimePeriodId" type="id-ne"></field>
      <field name="periodTypeId" type="id"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>	
      <prim-key field="standardTimePeriodId" />
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.common.sequence -->
  <!-- ========================================================= -->
	
    <entity entity-name="SequenceValueItem" 
            package-name="org.ofbiz.commonapp.common.sequence"
            title="Sequence Entity">
      <field name="seqName" type="id-long-ne"></field>
      <field name="seqId" type="numeric"></field>	
      <prim-key field="seqName" />
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.common.status -->
  <!-- ========================================================= -->
	
    <entity entity-name="StatusItem" 
            package-name="org.ofbiz.commonapp.common.status"
            title="Status Entity">
      <field name="statusId" type="id-ne"></field>
      <field name="statusTypeId" type="id"></field>
      <field name="sequenceId" type="id"></field>
      <field name="description" type="description"></field>	
      <prim-key field="statusId" />
      <relation type="one" rel-entity-name="StatusType">
        <key-map field-name="statusTypeId" />
      </relation>
      <relation type="many" rel-entity-name="OrderStatus">
        <key-map field-name="statusId" />
      </relation>
    </entity>	
    <entity entity-name="StatusType" 
            package-name="org.ofbiz.commonapp.common.status"
            title="Status Type Entity">
      <field name="statusTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="statusTypeId" />
      <relation type="one" title="Parent" rel-entity-name="StatusType">
        <key-map field-name="parentTypeId" rel-field-name="statusTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="StatusType">
        <key-map field-name="statusTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="StatusItem">
        <key-map field-name="statusTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.common.uom -->
  <!-- ========================================================= -->
	
    <entity entity-name="Uom" 
            package-name="org.ofbiz.commonapp.common.uom"
            title="Unit Of Measure Entity">
      <field name="uomId" type="id-ne"></field>
      <field name="uomTypeId" type="id"></field>
      <field name="abbreviation" type="short-varchar"></field>
      <field name="description" type="description"></field>	
      <prim-key field="uomId" />
      <relation type="one" rel-entity-name="UomType">
        <key-map field-name="uomTypeId" />
      </relation>
      <relation type="many" title="Main" rel-entity-name="UomConversion">
        <key-map field-name="uomId" />
      </relation>
      <relation type="many" title="ConvTo" rel-entity-name="UomConversion">
        <key-map field-name="uomId" rel-field-name="uomIdTo" />
      </relation>
    </entity>	
    <entity entity-name="UomConversion" 
            package-name="org.ofbiz.commonapp.common.uom"
            title="Unit Of Measure Conversion Type Entity">
      <field name="uomId" type="id-ne"></field>
      <field name="uomIdTo" type="id-ne"></field>
      <field name="conversionFactor" type="floating-point"></field>	
      <prim-key field="uomId" />	
      <prim-key field="uomIdTo" />
      <relation type="one" title="Main" rel-entity-name="Uom">
        <key-map field-name="uomId" />
      </relation>
      <relation type="one" title="ConvTo" rel-entity-name="Uom">
        <key-map field-name="uomIdTo" rel-field-name="uomId" />
      </relation>
    </entity>	
    <entity entity-name="UomType" 
            package-name="org.ofbiz.commonapp.common.uom"
            title="Unit Of Measure Type Entity">
      <field name="uomTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="uomTypeId" />
      <relation type="one" title="Parent" rel-entity-name="UomType">
        <key-map field-name="parentTypeId" rel-field-name="uomTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="UomType">
        <key-map field-name="uomTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="Uom">
        <key-map field-name="uomTypeId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.content.content -->
  <!-- ========================================================= -->
	
    <entity entity-name="Content" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Entity">
      <field name="contentId" type="id-ne"></field>
      <field name="contentTypeId" type="id"></field>
      <field name="statusId" type="id"></field>
      <field name="description" type="description"></field>
      <field name="fileLocation" type="long-varchar"></field>
      <field name="urlLocation" type="long-varchar"></field>	
      <prim-key field="contentId" />
      <relation type="one" rel-entity-name="StatusItem">
        <key-map field-name="statusId" />
      </relation>
      <relation type="one" rel-entity-name="ContentType">
        <key-map field-name="contentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ContentTypeAttr">
        <key-map field-name="contentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ContentAttribute">
        <key-map field-name="contentId" />
      </relation>
      <relation type="many" rel-entity-name="ContentDataObjectUsage">
        <key-map field-name="contentId" />
      </relation>
      <relation type="many" rel-entity-name="ContentCategoryClass">
        <key-map field-name="contentId" />
      </relation>
    </entity>	
    <entity entity-name="ContentAssociation" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Association Entity">
      <field name="contentIdFrom" type="id-ne"></field>
      <field name="contentIdTo" type="id-ne"></field>
      <field name="contactMechId" type="id"></field>
      <field name="functionTypeId" type="id"></field>
      <field name="upperLeftCoordinate" type="numeric"></field>	
      <prim-key field="contentIdFrom" />	
      <prim-key field="contentIdTo" />
    </entity>	
    <entity entity-name="ContentAttribute" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Attribute Entity">
      <field name="contentId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>
      <field name="attrValue" type="value"></field>	
      <prim-key field="contentId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="Content">
        <key-map field-name="contentId" />
      </relation>
      <relation type="many" rel-entity-name="ContentTypeAttr">
        <key-map field-name="attrName" />
      </relation>
    </entity>	
    <entity entity-name="ContentCategory" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Category Entity">
      <field name="contentCategoryId" type="id-ne"></field>
      <field name="parentCategoryId" type="id"></field>
      <field name="parentSeqId" type="id"></field>
      <field name="description" type="description"></field>	
      <prim-key field="contentCategoryId" />
      <relation type="one" rel-entity-name="ContentCategory">
        <key-map field-name="parentCategoryId" rel-field-name="contentCategoryId" />
      </relation>
      <relation type="many" rel-entity-name="ContentCategoryClass">
        <key-map field-name="contentCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ContentCategoryClass" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Category Classification Entity">
      <field name="contentCategoryId" type="id-ne"></field>
      <field name="contentId" type="id-ne"></field>
      <field name="seqId" type="id-ne"></field>	
      <prim-key field="contentCategoryId" />	
      <prim-key field="contentId" />	
      <prim-key field="seqId" />
      <relation type="one" rel-entity-name="Content">
        <key-map field-name="contentId" />
      </relation>
      <relation type="one" rel-entity-name="ContentCategory">
        <key-map field-name="contentCategoryId" />
      </relation>
    </entity>	
    <entity entity-name="ContentDataObjectUsage" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Data Object Usage Entity">
      <field name="contentId" type="id-ne"></field>
      <field name="dataObjectId" type="id-ne"></field>
      <field name="seqId" type="id-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>	
      <prim-key field="contentId" />	
      <prim-key field="dataObjectId" />	
      <prim-key field="seqId" />	
      <prim-key field="fromDate" />
      <relation type="one" rel-entity-name="Content">
        <key-map field-name="contentId" />
      </relation>
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
    </entity>	
    <entity entity-name="ContentRole" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Role Entity">
      <description>Data Type Of: Party Role</description>
      <field name="contentId" type="id-ne"></field>
      <field name="partyId" type="id-ne"></field>
      <field name="roleTypeId" type="id-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>	
      <prim-key field="contentId" />	
      <prim-key field="partyId" />	
      <prim-key field="roleTypeId" />	
      <prim-key field="fromDate" />
    </entity>	
    <entity entity-name="ContentType" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Type Entity">
      <field name="contentTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="contentTypeId" />
      <relation type="one" title="Parent" rel-entity-name="ContentType">
        <key-map field-name="parentTypeId" rel-field-name="contentTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="ContentType">
        <key-map field-name="contentTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ContentTypeAttr">
        <key-map field-name="contentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="Content">
        <key-map field-name="contentTypeId" />
      </relation>
    </entity>	
    <entity entity-name="ContentTypeAttr" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Content Type Attribute Entity">
      <field name="contentTypeId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>	
      <prim-key field="contentTypeId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="ContentType">
        <key-map field-name="contentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="ContentAttribute">
        <key-map field-name="attrName" />
      </relation>
      <relation type="many" rel-entity-name="Content">
        <key-map field-name="contentTypeId" />
      </relation>
    </entity>	
    <entity entity-name="DataObject" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Data Object Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="dataObjectTypeId" type="id"></field>
      <field name="description" type="description"></field>
      <field name="fileLocation" type="long-varchar"></field>
      <field name="dataObjectName" type="name"></field>	
      <prim-key field="dataObjectId" />
      <relation type="one" rel-entity-name="ElectronicText">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="one" rel-entity-name="ImageDataObject">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="one" rel-entity-name="OtherDataObject">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="many" rel-entity-name="ContentDataObjectUsage">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="one" rel-entity-name="DataObjectType">
        <key-map field-name="dataObjectTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DataObjectTypeAttr">
        <key-map field-name="dataObjectTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DataObjectAttribute">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="many" rel-entity-name="PartyDataObject">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="many" rel-entity-name="ProductDataObject">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="many" rel-entity-name="FeatureDataObject">
        <key-map field-name="dataObjectId" />
      </relation>
    </entity>	
    <entity entity-name="DataObjectAttribute" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Data Object Attribute Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>
      <field name="attrValue" type="value"></field>	
      <prim-key field="dataObjectId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="many" rel-entity-name="DataObjectTypeAttr">
        <key-map field-name="attrName" />
      </relation>
    </entity>	
    <entity entity-name="DataObjectPurpose" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Data Object Purpose Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="dataObjectPurposeTypeId" type="id-ne"></field>	
      <prim-key field="dataObjectId" />	
      <prim-key field="dataObjectPurposeTypeId" />
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
      <relation type="one" rel-entity-name="DataObjectPurposeType">
        <key-map field-name="dataObjectPurposeTypeId" />
      </relation>
    </entity>	
    <entity entity-name="DataObjectPurposeType" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Data Object Purpose Type Entity">
      <field name="dataObjectPurposeTypeId" type="id-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="dataObjectPurposeTypeId" />
      <relation type="many" rel-entity-name="DataObjectPurpose">
        <key-map field-name="dataObjectPurposeTypeId" />
      </relation>
    </entity>	
    <entity entity-name="DataObjectType" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Data Object Type Entity">
      <field name="dataObjectTypeId" type="id-ne"></field>
      <field name="parentTypeId" type="id-ne"></field>
      <field name="hasTable" type="indicator"></field>
      <field name="description" type="description"></field>	
      <prim-key field="dataObjectTypeId" />
      <relation type="one" title="Parent" rel-entity-name="DataObjectType">
        <key-map field-name="parentTypeId" rel-field-name="dataObjectTypeId" />
      </relation>
      <relation type="many" title="Child" rel-entity-name="DataObjectType">
        <key-map field-name="dataObjectTypeId" rel-field-name="parentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DataObjectTypeAttr">
        <key-map field-name="dataObjectTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DataObject">
        <key-map field-name="dataObjectTypeId" />
      </relation>
    </entity>	
    <entity entity-name="DataObjectTypeAttr" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Data Object Type Attribute Entity">
      <field name="dataObjectTypeId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>	
      <prim-key field="dataObjectTypeId" />	
      <prim-key field="attrName" />
      <relation type="one" rel-entity-name="DataObjectType">
        <key-map field-name="dataObjectTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DataObjectAttribute">
        <key-map field-name="attrName" />
      </relation>
      <relation type="many" rel-entity-name="DataObject">
        <key-map field-name="dataObjectTypeId" />
      </relation>
    </entity>	
    <entity entity-name="ElectronicText" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Electronic Text Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="textData" type="very-long"></field>	
      <prim-key field="dataObjectId" />
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
    </entity>	
    <entity entity-name="FunctionType" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Function Type Entity">
      <field name="functionTypeId" type="id-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="functionTypeId" />
    </entity>	
    <entity entity-name="ImageDataObject" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Image Data Object Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="imageData" type="blob"></field>	
      <prim-key field="dataObjectId" />
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
    </entity>	
    <entity entity-name="OtherDataObject" 
            package-name="org.ofbiz.commonapp.content.content"
            title="Other Data Object Entity">
      <field name="dataObjectId" type="id-ne"></field>
      <field name="dataObjectContent" type="blob"></field>	
      <prim-key field="dataObjectId" />
      <relation type="one" rel-entity-name="DataObject">
        <key-map field-name="dataObjectId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.content.document -->
  <!-- ========================================================= -->
	
    <entity entity-name="Document" 
            package-name="org.ofbiz.commonapp.content.document"
            title="Document Entity">
      <field name="documentId" type="id-ne"></field>
      <field name="documentTypeId" type="id"></field>
      <field name="dateCreated" type="date-time"></field>
      <field name="comments" type="comment"></field>
      <field name="documentLocation" type="long-varchar"></field>
      <field name="documentText" type="long-varchar"></field>
      <field name="imageData" type="blob"></field>	
      <prim-key field="documentId" />
      <relation type="one" rel-entity-name="DocumentType">
        <key-map field-name="documentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DocumentTypeAttr">
        <key-map field-name="documentTypeId" />
      </relation>
      <relation type="many" rel-entity-name="DocumentAttribute">
        <key-map field-name="documentId" />
      </relation>
    </entity>	
    <entity entity-name="DocumentAttribute" 
            package-name="org.ofbiz.commonapp.content.document"
            title="Document Attribute Entity">
      <field name="documentId" type="id-ne"></field>
      <field name="attrName" type="id-long-ne"></field>
      <field name="attrValue" type="value"></field>	
      <prim-key field="documentId" />	