<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
/**
 *  Title: Entity Engine Definitions for a Minimal Data Model (security, login, etc)
 *  Description: None
 *  Copyright (c) 2002 The Open For Business Project - www.ofbiz.org
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a 
 *  copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation 
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, and to permit persons to whom the 
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included 
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 *  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR 
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *@author David E. Jones (jonesde@ofbiz.org) 
 *@author Andy Zeneski (jaz@zsolv.com)
 *@version    1.0
 */
-->

<!DOCTYPE entitymodel [
    <!-- ====================== Root Element ======================= -->
    <!ELEMENT entitymodel ( title?, description?, copyright?, author?, version?, ( entity | view-entity )* )>
    <!-- ================= Children of entitymodel =================== -->
    <!ELEMENT title ( #PCDATA  )>
    <!ELEMENT description ( #PCDATA  )>
    <!ELEMENT copyright ( #PCDATA  )>
    <!ELEMENT author ( #PCDATA  )>
    <!ELEMENT version ( #PCDATA  )>
    <!ELEMENT entity ( description?, field+, prim-key*, relation* )>
    <!ELEMENT view-entity ( description?, member-entity+, alias+, view-link+, relation* )>
    <!-- ================== Children of entity ===================== -->
    <!-- see the children of entitymodel section for description, etc. -->
    <!ATTLIST entity
	entity-name CDATA #REQUIRED
	table-name CDATA #IMPLIED
	package-name CDATA #REQUIRED
	dependent-on CDATA #IMPLIED
	title CDATA #IMPLIED
	copyright CDATA #IMPLIED
	author CDATA #IMPLIED
	version CDATA #IMPLIED >
    <!ELEMENT field ( validate* )>
    <!ELEMENT prim-key EMPTY>
    <!ATTLIST prim-key
	field CDATA #REQUIRED >
    <!ELEMENT relation ( key-map+ )>
    <!-- ================== Children of view-entity ===================== -->
    <!-- see the children of entitymodel section for description, etc. -->
    <!ATTLIST view-entity
	entity-name CDATA #REQUIRED
	package-name CDATA #REQUIRED
	dependent-on CDATA #IMPLIED
	title CDATA #IMPLIED
	copyright CDATA #IMPLIED
	author CDATA #IMPLIED
	version CDATA #IMPLIED >
    <!ELEMENT member-entity EMPTY>
    <!ATTLIST member-entity
	entity-alias CDATA #REQUIRED
	entity-name CDATA #REQUIRED >
    <!ELEMENT alias EMPTY>
    <!ATTLIST alias
	entity-alias CDATA #REQUIRED
	name CDATA #REQUIRED
	field CDATA #IMPLIED 
        prim-key ( true | false ) "false" >
    <!ELEMENT view-link ( key-map+ )>
    <!ATTLIST view-link
	entity-alias CDATA #REQUIRED
	rel-entity-alias CDATA #REQUIRED >
    <!-- ==================== Children of field ===================== -->
    <!ATTLIST field
	name CDATA #REQUIRED >
    <!ATTLIST field
	col-name CDATA #IMPLIED >
    <!ATTLIST field
	type CDATA #REQUIRED >
    <!ELEMENT validate EMPTY>
    <!ATTLIST validate
	name CDATA #REQUIRED >
    <!-- ==================== Children of relation ====================== -->
    <!-- specifies whether or not the relation is a dependent one; ie if the related entity can exist without the main entity -->
    <!ATTLIST relation
	type ( one | many ) #REQUIRED
	title CDATA #IMPLIED
	rel-entity-name CDATA #REQUIRED >
    <!ELEMENT key-map EMPTY>
    <!-- see definition of relation in entity section above -->
    <!-- ===================== Children of key-map ====================== -->
    <!ATTLIST key-map
	field-name CDATA #REQUIRED >
    <!ATTLIST key-map
	rel-field-name CDATA #IMPLIED >
]>


<entitymodel>
  <!-- ========================================================= -->
  <!-- ======================== Defaults ======================= -->
  <!-- ========================================================= -->
    <title>Entity of an Open For Business Project Component</title>
    <description>None</description>
    <copyright>Copyright (c) 2002 The Open For Business Project - www.ofbiz.org</copyright>
    <author>None</author>
    <version>1.0</version>

  <!-- ========================================================= -->
  <!-- ======================== Data Model ===================== -->
  <!-- The modules in this file are as follows:                  -->
  <!--  - org.ofbiz.commonapp.common.sequence -->
  <!--  - org.ofbiz.commonapp.security.login -->
  <!--  - org.ofbiz.commonapp.security.securitygroup -->
  <!-- ========================================================= -->


  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.common.sequence -->
  <!-- ========================================================= -->

    <entity entity-name="SequenceValueItem" 
            package-name="org.ofbiz.commonapp.common.sequence"
            title="Sequence Entity">
      <field name="seqName" type="id-long-ne"></field>
      <field name="seqId" type="numeric"></field>	
      <prim-key field="seqName" />
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.security.login -->
  <!-- ========================================================= -->

    <entity entity-name="UserLogin" 
            package-name="org.ofbiz.commonapp.security.login"
            title="User Login Entity">
      <field name="userLoginId" type="id-vlong-ne"></field>
      <field name="partyId" type="id"></field>
      <field name="currentPassword" type="short-varchar"></field>
      <field name="passwordHint" type="description"></field>	
      <prim-key field="userLoginId" />
      <relation type="one" rel-entity-name="Party">
        <key-map field-name="partyId" />
      </relation>
      <relation type="many" rel-entity-name="UserLoginSecurityGroup">
        <key-map field-name="userLoginId" />
      </relation>
      <relation type="many" rel-entity-name="UserLoginHistory">
        <key-map field-name="userLoginId" />
      </relation>
      <relation type="one" rel-entity-name="Person">
        <key-map field-name="partyId" />
      </relation>
    </entity>
    <entity entity-name="UserLoginHistory" 
            package-name="org.ofbiz.commonapp.security.login"
            title="User Login History Entity">
      <field name="userLoginId" type="id-vlong-ne"></field>
      <field name="fromDate" type="date-time"></field>
      <field name="thruDate" type="date-time"></field>
      <field name="partyId" type="id"></field>
      <field name="referrerUrl" type="url"></field>
      <field name="passwordUsed" type="short-varchar"></field>	
      <prim-key field="userLoginId" />	
      <prim-key field="fromDate" />
      <relation type="one" rel-entity-name="UserLogin">
        <key-map field-name="userLoginId" />
      </relation>
      <relation type="one" rel-entity-name="Party">
        <key-map field-name="partyId" />
      </relation>
    </entity>

  <!-- ========================================================= -->
  <!-- org.ofbiz.commonapp.security.securitygroup -->
  <!-- ========================================================= -->

    <entity entity-name="SecurityGroup" 
            package-name="org.ofbiz.commonapp.security.securitygroup"
            title="Security Component - Security Group Entity">
      <field name="groupId" type="id-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="groupId" />
      <relation type="many" rel-entity-name="UserLoginSecurityGroup">
        <key-map field-name="groupId" />
      </relation>
      <relation type="many" rel-entity-name="SecurityGroupPermission">
        <key-map field-name="groupId" />
      </relation>
    </entity>
    <entity entity-name="SecurityGroupPermission" 
            package-name="org.ofbiz.commonapp.security.securitygroup"
            title="Security Component - Security Group Permission Entity">
      <description>Defines a permission available to a security group</description>
      <field name="groupId" type="id-ne"></field>
      <field name="permissionId" type="id-long-ne"></field>	
      <prim-key field="groupId" />	
      <prim-key field="permissionId" />
      <relation type="one" rel-entity-name="SecurityGroup">
        <key-map field-name="groupId" />
      </relation>
      <relation type="one" rel-entity-name="SecurityPermission">
        <key-map field-name="permissionId" />
      </relation>
    </entity>
    <entity entity-name="SecurityPermission" 
            package-name="org.ofbiz.commonapp.security.securitygroup"
            title="Security Component - Security Permission Entity">
      <field name="permissionId" type="id-long-ne"></field>
      <field name="description" type="description"></field>	
      <prim-key field="permissionId" />
      <relation type="many" rel-entity-name="SecurityGroupPermission">
        <key-map field-name="permissionId" />
      </relation>
    </entity>
    <entity entity-name="UserLoginSecurityGroup" 
            package-name="org.ofbiz.commonapp.security.securitygroup"
            title="Security Component - User Login Security Group Entity">
      <description>Maps a UserLogin to a security group</description>
      <field name="userLoginId" type="id-vlong-ne"></field>
      <field name="groupId" type="id-ne"></field>	
      <prim-key field="userLoginId" />	
      <prim-key field="groupId" />
      <relation type="one" rel-entity-name="UserLogin">
        <key-map field-name="userLoginId" />
      </relation>
      <relation type="one" rel-entity-name="SecurityGroup">
        <key-map field-name="groupId" />
      </relation>
      <relation type="many" rel-entity-name="SecurityGroupPermission">
        <key-map field-name="groupId" />
      </relation>
    </entity>  
</entitymodel>

