=== delan/OFBiz/core/docs/services.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT services (description, vendor, version, created, service+)>
<!ELEMENT description ANY>
<!ELEMENT vendor (#PCDATA)>
<!ELEMENT created (#PCDATA)>
<!ELEMENT service (attribute*)>
<!ATTLIST service
	name CDATA #REQUIRED
	engine CDATA #REQUIRED
	location CDATA #REQUIRED
	invoke CDATA #REQUIRED
	export (true|false) #IMPLIED
>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	mode (IN|OUT|INOUT) #REQUIRED
>

=== delan/OFBiz/commonapp/globalservices/services_shipment.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE services PUBLIC "-//OFBiz//DTD Services Config//EN" "http://www.ofbiz.org/dtds/services.dtd">

<services>
    <description>Common Application Components Shipment Services</description>
    <vendor>OFBiz</vendor>
    <version>1.0</version>
    
    <!-- Receipt Services -->    
    <service name="interfaceShipmentReceipt" engine="interface" location="" invoke="">
    	<description>ShipmentReceipt Interface</description>
    	<attribute name="inventoryItemId" type="String" mode="IN" optional="false"/>
    	<attribute name="productId" type="String" mode="IN" optional="false"/>
    	<attribute name="shipmentPackageId" type="String" mode="IN" optional="true"/>
    	<attribute name="orderId" type="String" mode="IN" optional="true"/>
    	<attribute name="orderItemSeqId" type="String" mode="IN" optional="true"/>
    	<attribute name="returnId" type="String" mode="IN" optional="true"/>
    	<attribute name="returnItemSeqId" type="String" mode="IN" optional="true"/>
    	<attribute name="rejectionId" type="String" mode="IN" optional="true"/>
    	<attribute name="datetimeReceived" type="Timestamp" mode="IN" optional="true"/>
    	<attribute name="itemDescription" type="String" mode="IN" optional="true"/>
    	<attribute name="quantityAccepted" type="Double" mode="IN" optional="false"/>
    	<attribute name="quantityRejected" type="Double" mode="IN" optional="false"/>    	
    </service>
    <service name="createShipmentReceipt" engine="simple"
    		location="org/ofbiz/commonapp/shipment/receipt/ShipmentReceiptServices.xml" invoke="createShipmentReceipt" auth="true">
    	<description>Creates a ShipmentReceipt Record</description>
		<implements service="interfaceShipmentReceipt"/>    	
    	<attribute name="receiptId" type="String" mode="OUT" optional="false"/>
    </service>
    
    <service name="prepareInventoryReceipt" engine="simple"
    		location="org/ofbiz/commonapp/shipment/receipt/ShipmentReceiptServices.xml" invoke="prepareInventoryReceipt" auth="true">
    	<description>Prepare Receipt Form for Inventory Item</description>
    	<attribute name="quantityAccepted" type="Double" mode="IN" optional="false"/>
    	<attribute name="inventoryItemTypeId" type="String" mode="IN" optional="false"/>
    	<attribute name="quantityOnHand" type="Double" mode="OUT" optional="true"/>
    	<attribute name="availableToPromise" type="Double" mode="OUT" optional="true"/>
    </service>
    <service name="receiveInventoryProduct" engine="group" location="receiveInventoryProduct" invoke="" auth="true">
    	<attribute name="inventoryItemId" type="String" mode="INOUT" optional="true"/>
    	<attribute name="availableToPromise" type="Double" mode="INOUT" optional="true"/>
    	<attribute name="quantityOnHand" type="Double" mode="INOUT" optional="true"/>
    </service>
    
    <service name="interfaceShipmentReceiptRole" engine="interface" location="" invoke="">
    	<description>Interface for ShipmentReceiptRole</description>
    	<attribute name="receiptId" type="String" mode="IN" optional="false"/>
    	<attribute name="partyId" type="String" mode="IN" optional="false"/>
    	<attribute name="roleTypeId" type="String" mode="IN" optional="false"/>
    </service>
    <service name="createShipmentReceiptRole" engine="simple"
    		location="org/ofbiz/commonapp/shipment/receipt/ShipmentReceiptServices.xml" invoke="createShipmentReceiptRole" auth="true">
    	<description>Create a ShipmentReceipt Role entry</description>
    	<implements service="interfaceShipmentReceiptRole"/>
    </service>
    <service name="removeShipmentReceiptRole" engine="simple"
    		location="org/ofbiz/commonapp/shipment/receipt/ShipmentReceiptServices.xml" invoke="removeShipmentReceiptRole" auth="true">
    	<description>Remove a ShipmentReceipt Role entry</description>
    	<implements service="interfaceShipmentReceiptRole"/>
    </service>

    <!-- Shipment Estimate (Rate) Services -->
    <service name="createShipmentEstimate" engine="java"
                location="org.ofbiz.commonapp.shipment.shipment.ShipmentServices" invoke="createShipmentEstimate" auth="true">
        <description>Create Shipment Estimate</description>
        <attribute name="shipMethod" type="String" mode="IN" optional="false"/>
        <attribute name="toGeo" type="String" mode="IN" optional="true"/>
        <attribute name="fromGeo" type="String" mode="IN" optional="true"/>
        <attribute name="partyId" type="String" mode="IN" optional="true"/>
        <attribute name="roleTypeId" type="String" mode="IN" optional="true"/>
        <attribute name="flatPercent" type="Double" mode="IN" optional="false"/>
        <attribute name="flatPrice" type="Double" mode="IN" optional="true"/>
        <attribute name="flatItemPrice" type="Double" mode="IN" optional="true"/>
        <attribute name="wmin" type="Double" mode="IN" optional="true"/>
        <attribute name="wmax" type="Double" mode="IN" optional="true"/>
        <attribute name="wprice" type="Double" mode="IN" optional="true"/>
        <attribute name="wuom" type="String" mode="IN" optional="true"/>
        <attribute name="qmin" type="Double" mode="IN" optional="true"/>
        <attribute name="qmax" type="Double" mode="IN" optional="true"/>
        <attribute name="qprice" type="Double" mode="IN" optional="true"/>
        <attribute name="quom" type="String" mode="IN" optional="true"/>
        <attribute name="pmin" type="Double" mode="IN" optional="true"/>
        <attribute name="pmax" type="Double" mode="IN" optional="true"/>
        <attribute name="pprice" type="Double" mode="IN" optional="true"/>
        <attribute name="puom" type="String" mode="IN" optional="true"/>
        <attribute name="shipmentCostEstimateId" type="String" mode="OUT"/>
    </service>

    <service name="removeShipmentEstimate" engine="java"
                location="org.ofbiz.commonapp.shipment.shipment.ShipmentServices" invoke="removeShipmentEstimate" auth="true">
        <description>Remove Shipment Estimate</description>
        <attribute name="shipmentCostEstimateId" type="String" mode="IN" optional="false"/>
    </service>
</services>
